In [1]:
import numpy as np
import pandas as pd

string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [2]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA
import pandas as pd

data = pd.Series([1, NA, 3.5, NA, 7])

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [18]:
x=data.dropna(how='all')
x

0    1.0
2    3.5
4    7.0
dtype: float64

In [22]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data
cleaned

0    1    2
0  1.0  6.5  3.0

In [13]:
import pandas as pd 
from numpy import nan as NA
df = pd.DataFrame(np.random.randn(7, 3))
df
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df


0         1         2
0  1.576940       NaN       NaN
1 -0.097891       NaN       NaN
2  1.000240       NaN -0.468117
3 -1.518645       NaN -1.422842
4 -0.584812  2.342497  0.026670
5 -0.292110  1.050318  1.294500
6 -0.113183 -0.270872  1.208772

In [14]:
ch=df.fillna({1: 0.5, 2: 0})
ch


0         1         2
0  1.576940  0.500000  0.000000
1 -0.097891  0.500000  0.000000
2  1.000240  0.500000 -0.468117
3 -1.518645  0.500000 -1.422842
4 -0.584812  2.342497  0.026670
5 -0.292110  1.050318  1.294500
6 -0.113183 -0.270872  1.208772

In [15]:
df.fillna(0, inplace=True)
df

0         1         2
0  1.576940  0.000000  0.000000
1 -0.097891  0.000000  0.000000
2  1.000240  0.000000 -0.468117
3 -1.518645  0.000000 -1.422842
4 -0.584812  2.342497  0.026670
5 -0.292110  1.050318  1.294500
6 -0.113183 -0.270872  1.208772

In [16]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df
df.fillna(method='ffill')
df.fillna(method='ffill', limit=2)

0         1         2
0  0.324943  2.138004 -0.204693
1 -1.044398  0.941860 -0.228547
2  0.009042  0.941860  2.059398
3 -0.862462  0.941860  0.223473
4  1.081424       NaN  0.223473
5 -0.739890       NaN  0.223473

In [9]:
import pandas as pd
import numpy as np

data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
 'corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data


food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [10]:
meat_to_animal = {'bacon': 'pig','pulled pork': 'pig','pastrami': 'cow','corned beef': 'cow','honey ham': 'pig','nova lox': 'salmon'}
meat_to_animal


{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [11]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data



food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [12]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [15]:
import pandas as pd
from numpy import nan as NA
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [22]:
R1=data.replace(-999, np.nan)
R1

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [27]:
R2=data.replace([-999, -1000], np.nan)
R2

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [24]:
R3=data.replace([-999, -1000], [np.nan, 0])
R3

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [26]:
R4=data.replace({-999: np.nan, -1000: 0}) 
R4

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [79]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
transform = lambda x: x[:4].upper()
data.index.map(transform)


Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [80]:
data.index = data.index.map(transform)
data.index
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [86]:
data.rename(index=str.title, columns=str.upper)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [85]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'THREE': 'peekaboo'})

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [53]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)


In [87]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
ages


[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [88]:
bins = [18, 25, 35, 60, 100]


In [89]:
cats = pd.cut(ages, bins) 
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [90]:
cats.codes


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [91]:
cats.categories



IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [92]:
pd.value_counts(cats)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [94]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)


[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [97]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [99]:
data = np.random.rand(20)
data

array([0.18430551, 0.33487785, 0.37877731, 0.46756898, 0.48634794,
       0.11235613, 0.96389312, 0.70507106, 0.60656345, 0.0385564 ,
       0.98519928, 0.86476443, 0.83638985, 0.05478048, 0.73365514,
       0.80465347, 0.67550004, 0.92015545, 0.77853126, 0.02428193])

In [105]:
data1=pd.cut(data, 4, precision=2)
data1.categories


IntervalIndex([(0.023, 0.26], (0.26, 0.5], (0.5, 0.74], (0.74, 0.99]], dtype='interval[float64, right]')

In [108]:
data = np.random.randn(1000) # Normally distributed
data

array([ 3.12406310e-01, -8.12044621e-01, -2.67950933e-01, -4.25270190e-01,
       -7.21278272e-02,  5.13312939e-01,  1.77163044e-01, -1.59637968e+00,
       -1.05732777e+00,  5.66831689e-01, -6.92306539e-01, -1.21932142e+00,
       -1.88677473e+00, -2.96537191e-02, -7.91470940e-01,  4.85781898e-01,
       -1.62904834e+00,  7.99066541e-01,  8.62059638e-01,  8.15627011e-02,
        1.13266195e+00, -2.58944406e-01,  1.22907845e+00,  1.35646254e+00,
       -1.09564486e+00, -1.70823997e+00, -1.17499349e+00,  4.52459151e-02,
       -3.88114020e-01,  8.50538896e-01, -1.75310566e+00, -9.80768557e-01,
       -7.59664925e-01, -1.06990843e+00, -3.01765724e-02,  6.66618841e-01,
        2.27488445e-01, -6.71540980e-01, -2.93416949e-01,  7.82917182e-01,
       -3.50006612e-01, -8.65930198e-02, -2.68233224e-01,  4.58426566e-01,
        2.13510527e+00,  1.60100743e+00, -1.30484747e-01, -7.18146366e-01,
       -5.85624292e-01,  7.62721738e-01, -8.35783254e-01, -1.60263038e+00,
       -1.03591348e+00, -

In [110]:
cats = pd.qcut(data, 4) # Cut into quartiles
cats.codes

array([2, 0, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 3, 3, 2, 3, 1,
       3, 3, 0, 0, 0, 2, 1, 3, 0, 0, 0, 0, 1, 2, 2, 0, 1, 3, 1, 1, 1, 2,
       3, 3, 1, 0, 1, 3, 0, 0, 0, 1, 1, 1, 3, 0, 2, 1, 3, 1, 2, 1, 2, 2,
       0, 0, 3, 3, 3, 0, 0, 1, 1, 3, 0, 1, 2, 3, 2, 1, 2, 1, 2, 0, 0, 3,
       0, 1, 3, 2, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 3, 1, 3, 1, 2, 2, 1, 2,
       2, 2, 3, 0, 1, 0, 3, 3, 1, 3, 0, 3, 2, 3, 2, 3, 2, 3, 0, 3, 3, 1,
       0, 1, 2, 3, 3, 2, 0, 1, 3, 2, 2, 2, 2, 2, 0, 0, 3, 1, 1, 1, 1, 0,
       2, 3, 3, 2, 0, 0, 3, 2, 2, 3, 0, 2, 1, 2, 3, 2, 1, 1, 0, 1, 3, 0,
       3, 3, 3, 3, 2, 2, 0, 1, 2, 1, 3, 3, 0, 1, 2, 1, 3, 0, 1, 0, 3, 2,
       3, 2, 0, 0, 2, 0, 0, 2, 2, 3, 0, 2, 3, 0, 1, 0, 1, 2, 1, 0, 0, 1,
       2, 3, 2, 3, 2, 2, 1, 0, 0, 1, 3, 3, 3, 2, 0, 3, 2, 0, 0, 1, 0, 0,
       3, 3, 2, 2, 0, 3, 2, 2, 2, 2, 1, 0, 2, 3, 2, 2, 3, 3, 1, 1, 2, 3,
       2, 2, 3, 3, 3, 1, 2, 3, 0, 2, 1, 3, 3, 0, 0, 1, 1, 3, 3, 2, 0, 0,
       3, 2, 2, 0, 2, 1, 0, 3, 3, 1, 1, 0, 2, 0, 0,

In [115]:
x=pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])
pd.value_counts(x)


(-1.24, 0.0323]                 400
(0.0323, 1.328]                 400
(-3.5229999999999997, -1.24]    100
(1.328, 3.873]                  100
dtype: int64