In [1]:
#Muhammad Hidayat Hidayat Bin Mohd Yusof
#20FFTT2910
#DA3304 APPLIED PROGRAMMING FOR DATA ANALYTICS
import pandas as pd
import numpy as np
data=pd.read_csv('Social_Network_Ads.csv')
target=data.pop('Purchased')
data

User ID  Gender  Age  EstimatedSalary
0    15624510    Male   19            19000
1    15810944    Male   35            20000
2    15668575  Female   26            43000
3    15603246  Female   27            57000
4    15804002    Male   19            76000
..        ...     ...  ...              ...
395  15691863  Female   46            41000
396  15706071    Male   51            23000
397  15654296  Female   50            20000
398  15755018    Male   36            33000
399  15594041  Female   49            36000

[400 rows x 4 columns]

In [2]:
data['Gender'].replace(to_replace={'Male':0,'Female':1},inplace=True)

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as sm
from sklearn.model_selection import cross_val_score
X_train, X_test, y_train, y_test = train_test_split(data, target,test_size=0.2,train_size=0.8, random_state=24)
knn=KNeighborsClassifier(n_neighbors=29)
knn.fit(X_train,y_train)

y_pred=knn.predict(X_test)

cvscore = cross_val_score(knn, X_test, y_test, cv=5)

print('Accuracy = {:.2f}'.format(knn.score(X_test,y_test)))
print('Recall = {:.2f}'.format(sm.recall_score(y_test,y_pred)))
print('Precision = {:.2f}'.format(sm.precision_score(y_test,y_pred)))
print('F1 Score = {:.2f}'.format(sm.f1_score(y_test,y_pred)))
print("Average cross-validation scores: {}".format(cvscore.mean()))
print('Confusion matrix:\n',sm.confusion_matrix(y_test,y_pred))

Accuracy = 0.86
Recall = 0.64
Precision = 0.95
F1 Score = 0.77
Average cross-validation scores: 0.65
Confusion matrix:
 [[51  1]
 [10 18]]


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import sklearn.metrics as sm
from sklearn.model_selection import cross_val_score
X_train, X_test, y_train, y_test = train_test_split(data, target,test_size=0.2,train_size=0.8, random_state=24)
gaus=GaussianNB()
gaus.fit(X_train,y_train)

y_pred=gaus.predict(X_test)

cvscore = cross_val_score(gaus, X_test, y_test, cv=5)

print('Accuracy = {:.2f}'.format(knn.score(X_test,y_test)))
print('Recall = {:.2f}'.format(sm.recall_score(y_test,y_pred)))
print('Precision = {:.2f}'.format(sm.precision_score(y_test,y_pred)))
print('F1 Score = {:.2f}'.format(sm.f1_score(y_test,y_pred)))
print("Average cross-validation scores: {}".format(cvscore.mean()))
print('Confusion matrix:\n',sm.confusion_matrix(y_test,y_pred))

Accuracy = 0.86
Recall = 0.93
Precision = 1.00
F1 Score = 0.96
Average cross-validation scores: 0.875
Confusion matrix:
 [[52  0]
 [ 2 26]]


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as sm
from sklearn.model_selection import cross_val_score
X_train, X_test, y_train, y_test = train_test_split(data, target,test_size=0.2,train_size=0.8, random_state=24)
dt=DecisionTreeClassifier(max_depth=3)
dt.fit(X_train,y_train)

y_pred=dt.predict(X_test)

cvscore = cross_val_score(dt, X_test, y_test, cv=5)

print('Accuracy = {:.2f}'.format(dt.score(X_test,y_test)))
print('Recall = {:.2f}'.format(sm.recall_score(y_test,y_pred)))
print('Precision = {:.2f}'.format(sm.precision_score(y_test,y_pred)))
print('F1 Score = {:.2f}'.format(sm.f1_score(y_test,y_pred)))
print("Average cross-validation scores: {}".format(cvscore.mean()))
print('Confusion matrix:\n',sm.confusion_matrix(y_test,y_pred))

Accuracy = 0.94
Recall = 0.86
Precision = 0.96
F1 Score = 0.91
Average cross-validation scores: 0.95
Confusion matrix:
 [[51  1]
 [ 4 24]]


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as sm
X_train, X_test, y_train, y_test = train_test_split(data, target,test_size=0.2,train_size=0.8, random_state=24)
lr=LogisticRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

cvscore = cross_val_score(lr, X_test, y_test, cv=5)

print('Accuracy = {:.2f}'.format(lr.score(X_test,y_test)))
print('Recall = {:.2f}'.format(sm.recall_score(y_test,y_pred)))
print('Precision = {:.2f}'.format(sm.precision_score(y_test,y_pred)))
print('F1 Score = {:.2f}'.format(sm.f1_score(y_test,y_pred)))
print("Average cross-validation scores: {}".format(cvscore.mean()))
print('Confusion matrix:\n',sm.confusion_matrix(y_test,y_pred))

Accuracy = 0.88
Recall = 0.64
Precision = 1.00
F1 Score = 0.78
Average cross-validation scores: 0.875
Confusion matrix:
 [[52  0]
 [10 18]]


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import sklearn.metrics as sm
X_train, X_test, y_train, y_test = train_test_split(data, target,test_size=0.2,train_size=0.8, random_state=24)
svm=SVC(C=3,kernel='linear')
svm.fit(X_train,y_train)

y_pred=svm.predict(X_test)

cvscore = cross_val_score(svm, X_test, y_test, cv=5)

print('Accuracy = {:.2f}'.format(svm.score(X_test,y_test)))
print('Recall = {:.2f}'.format(sm.recall_score(y_test,y_pred)))
print('Precision = {:.2f}'.format(sm.precision_score(y_test,y_pred)))
print('F1 Score = {:.2f}'.format(sm.f1_score(y_test,y_pred)))
print("Average cross-validation scores: {}".format(cvscore.mean()))
print('Confusion matrix:\n',sm.confusion_matrix(y_test,y_pred))

Accuracy = 0.86
Recall = 0.61
Precision = 1.00
F1 Score = 0.76
Average cross-validation scores: 0.8375
Confusion matrix:
 [[52  0]
 [11 17]]
